//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.15 at 09:08:32 AM MSK 
//


package com.company.model.xjc;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.company.model.xjc package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Journal_QNAME = new QName("", "journal");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.company.model.xjc
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Journal }
     * 
     */
    public Journal createJournal() {
        return new Journal();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Journal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "journal")
    public JAXBElement<Journal> createJournal(Journal value) {
        return new JAXBElement<Journal>(_Journal_QNAME, Journal.class, null, value);
    }

}
